# Generated by Django 5.1 on 2024-10-27 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('titre', models.CharField(max_length=32)),
                ('sortie', models.DateField(unique=True)),
                ('sujet', models.TextField()),
                ('note', models.FloatField()),
                ('like', models.IntegerField(default=0)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Documentaire',
                'verbose_name_plural': 'Documentaires',
            },
        ),
        migrations.CreateModel(
            name='Jury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('nom', models.CharField(max_length=32)),
                ('prenoms', models.CharField(max_length=130)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_naissance', models.DateField()),
                ('password', models.CharField(max_length=128)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('president', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Jury',
                'verbose_name_plural': 'Jurys',
            },
        ),
        migrations.CreateModel(
            name='Producteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('nom', models.CharField(max_length=32)),
                ('prenoms', models.CharField(max_length=130)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_naissance', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Producteur',
                'verbose_name_plural': 'Producteurs',
            },
        ),
        migrations.CreateModel(
            name='Realisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('nom', models.CharField(max_length=32)),
                ('prenoms', models.CharField(max_length=130)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_naissance', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Réalisateur',
                'verbose_name_plural': 'Réalisateurs',
            },
        ),
        migrations.CreateModel(
            name='Resp_Insp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=32)),
                ('prenoms', models.CharField(max_length=130)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name': "Responsable d'inspection",
                'verbose_name_plural': "Responsables d'inspection",
            },
        ),
        migrations.CreateModel(
            name='Resp_Prod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=32)),
                ('prenoms', models.CharField(max_length=130)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Responsable de production',
                'verbose_name_plural': 'Responsables de production',
            },
        ),
        migrations.CreateModel(
            name='Planning_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure', models.TimeField()),
                ('documentaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DAT.documentaire')),
            ],
        ),
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('planning_item_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_item_1', to='DAT.planning_item')),
                ('planning_item_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_item_2', to='DAT.planning_item')),
                ('planning_item_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_item_3', to='DAT.planning_item')),
            ],
        ),
        migrations.AddField(
            model_name='documentaire',
            name='producteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DAT.producteur'),
        ),
        migrations.AddField(
            model_name='documentaire',
            name='realisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DAT.realisateur'),
        ),
    ]
