# Generated by Django 5.1 on 2024-11-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DAT', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentaire',
            name='note',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='documentaire',
            name='sortie',
            field=models.DateField(),
        ),
    ]
