# Generated by Django 5.1 on 2024-11-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DAT', '0002_alter_documentaire_note_alter_documentaire_sortie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentaire',
            name='note',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
